# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='images/', width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('description', models.TextField(max_length=2000)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('delivery_date', models.DateTimeField()),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.Computer')),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Count', to='my_app.Computer')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=50, unique=True)),
                ('last_name', models.CharField(max_length=50, unique=True)),
                ('middle_name', models.CharField(max_length=50, unique=True)),
                ('birthday', models.DateField()),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], default='М', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.User'),
        ),
        migrations.AddField(
            model_name='computer',
            name='usr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.User'),
        ),
    ]
